---

- name: install
  package:
    name: "{{ item }}"
  with_items: "{{ _pp_packages }}"
  register: php_install

- name: httpd service
  service:
    name: "{{ _pp_httpd_service }}"
    state: started
  ignore_errors: true
  check_mode: true
  changed_when: false
  register: httpd_service

- name: httpd restart
  service:
    name: "{{ _pp_httpd_service }}"
    state: started
  # restart if php is installed and httpd service is up and running
  # this check is only compatible with systemd; always restart else
  when: |
    php_install.changed
    and httpd_service['status']['ActiveState'] | default('active') == 'active'
